version: "3.7"

services:
  ttk-backend:
    image: mojaloop/ml-testing-toolkit:v15.0.0
    user: root
    volumes:
      - "./ttk/spec_files:/opt/app/spec_files"
      - "./ttk/examples:/opt/app/examples"
    ports:
      - "4040:4040"
      - "5050:5050"
    command:
      - sh
      - -c
      - "npm start"

  ttk-ui:
    image: mojaloop/ml-testing-toolkit-ui:v15.1.0-snapshot.0
    ports:
      - "6060:6060"
    environment:
      - API_BASE_URL=http://localhost:5050
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh

  gsp-connector-svc:
    image: mojaloop/gsp-connector:local
    container_name: gsp-connector-svc
    build:
      context: ./gsp-connector
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/gsp-connector-conf.json:/opt/app/config/default.json:ro
    ## Useful for debugging
    # command:
    #   - sh
    #   - -c
    #   - "sleep infinity"
    user: root # Set Root so we can install Curl for Healthchecks
    healthcheck:
      test: [
        "CMD" ,
        "apk", "add", "--no-cache", "curl", # Install curl
        "&&",
        "curl", "-f", "http://localhost:3000" # Check if api is up
        ]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

networks:
  default:
    name: mojaloop-testing-toolkit
